grupo/control/urls.py
from django.urls import path

from . import views

app_name = 'control'
urlpatterns = [
    path('', views.index, name='index')
]

urlpatterns += [
    path('personas/', views.PersonaListView.as_view(), name='personas'),
    path('persona/<int:pk>', views.PersonaDetailView.as_view(), name='persona-detail'),
    path('comunidades/', views.ComunidadListView.as_view(), name='comunidades'),
    path('comunidad/<int:pk>', views.ComunidadDetailView.as_view(), name='comunidad-detail'),
    path('actividades/', views.ActividadListView.as_view(), name='actividades'),
    path('actividad/<int:pk>', views.ActividadDetailView.as_view(), name='actividad-detail'),
]

# Add URLConf to create, update, and delete authors
urlpatterns += [
    path('persona/create/', views.PersonaCreate.as_view(), name='persona_create'),
    path('persona/<int:pk>/update/', views.PersonaUpdate.as_view(), name='persona_update'),
    path('persona/<int:pk>/delete/', views.PersonaDelete.as_view(), name='persona_delete'),
]

urlpatterns += [
    path('comunidad/create/', views.ComunidadCreate.as_view(), name='comunidad_create'),
    path('comunidad/<int:pk>/update/', views.ComunidadUpdate.as_view(), name='comunidad_update'),
    path('comunidad/<int:pk>/delete/', views.ComunidadDelete.as_view(), name='comunidad_delete'),
]

urlpatterns += [
    path('actividad/create/', views.ActividadCreate.as_view(), name='actividad_create'),
    path('actividad/<int:pk>/update/', views.ActividadUpdate.as_view(), name='actividad_update'),
    path('actividad/<int:pk>/delete/', views.ActividadDelete.as_view(), name='actividad_delete'),
]

grupo/grupo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('control/', include('control.urls'))
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/control/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

grupo/control/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from datetime import datetime, date

# Create your models here.
class Comunidad(models.Model):
    nombre_comunidad = models.CharField(max_length=100)
    departamento = models.CharField(max_length=100)
    municipio = models.CharField(max_length=100)

    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Persona(update etc)
        """
        return reverse('control:comunidad-detail', args=[str(self.id)])

    def __str__(self):
        return self.nombre_comunidad

class Persona(models.Model):
    nombre_persona = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    edad = models.IntegerField()

    comunidad = models.ForeignKey(Comunidad, on_delete=models.SET_NULL, null=True)
    
    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Persona(update etc)
        """
        return reverse('control:persona-detail', args=[str(self.id)])

    def __str__(self):
        return self.nombre_persona

class Actividad(models.Model):
    nombre_actividad = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200)
    fecha = models.DateField(default=datetime.now, null=True, blank=True)
    lugar = models.CharField(max_length=200)

    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Persona(update etc)
        """
        return reverse('control:actividad-detail', args=[str(self.id)])

    def __str__(self):
        return self.nombre_actividad

class Participantes_Actividad(models.Model):
    actividad = models.ForeignKey(Actividad, db_column='actividad_id', on_delete=models.SET_NULL, null=True)
    persona = models.ForeignKey(Persona, db_column='persona_id', on_delete=models.SET_NULL, null=True, verbose_name='Participantes')

grupo/control/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from .models import Actividad, Participantes_Actividad, Persona, Comunidad

from django.forms import SelectDateWidget
from django.utils import timezone

# ------------------------------------

class ActividadForm(ModelForm):

    def __init__(self, *args, **kwargs):
            super(ActividadForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'

    class Meta:

        model = Actividad
        fields = '__all__'
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'})
        }

# ------------------------------------

class PersonaForm(ModelForm):
    comunidad = forms.ModelChoiceField(queryset=Comunidad.objects.all(),empty_label="Seleccione una Comunidad")

    def __init__(self, *args, **kwargs):
            super(PersonaForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Persona
        fields = '__all__'
        widgets = {
                'nombre_persona': forms.TextInput(attrs={'class': 'input', 'autofocus': True}),
            }

# ------------------------------------

class ComunidadForm(ModelForm):

    def __init__(self, *args, **kwargs):
            super(ComunidadForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Comunidad
        fields = '__all__'
    
# ------------------------------------

class PartActForm(ModelForm):
    persona = forms.ModelChoiceField(queryset=Persona.objects.all(),empty_label="Seleccione un Participante")

    def __init__(self, *args, **kwargs):
            super(PartActForm, self).__init__(*args, **kwargs)
            self.fields['persona'].widget.attrs\
            .update({
                'class': 'form-control'
            })

    class Meta:
        model = Participantes_Actividad
        exclude = ()

PartActFormSet = inlineformset_factory(Actividad, Participantes_Actividad, form=PartActForm, extra=3, can_delete=True)

# ------------------------------------

grupo/control/views.py
from django.shortcuts import render

# Create your views here.
from .models import Persona, Comunidad, Actividad

def index(request):
    return render(request, 'control/dashboard.html')


# def personas(request):
#    return render(request, 'control/persona/listar.html')

    
from django.views import generic

class PersonaListView(generic.ListView):
    model = Persona
    paginate_by = 10

class PersonaDetailView(generic.DetailView):
    model = Persona

# ------------------------------------

class ComunidadListView(generic.ListView):
    model = Comunidad
    paginate_by = 10

class ComunidadDetailView(generic.DetailView):
    model = Comunidad

# ------------------------------------

class ActividadListView(generic.ListView):
    model = Actividad
    paginate_by = 10

class ActividadDetailView(generic.DetailView):
    model = Actividad

# ------------------------------------

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Persona, Comunidad, Actividad, Participantes_Actividad

from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator

from .forms import *

class PersonaCreate(CreateView):
    model = Persona
    # fields = '__all__'
    form_class = PersonaForm
    success_url = reverse_lazy('control:personas')
    template_name_suffix = '_crear'

    @method_decorator(permission_required('control.add_persona',reverse_lazy('control:personas')))
    def dispatch(self, *args, **kwargs):
            return super(PersonaCreate, self).dispatch(*args, **kwargs)

class PersonaUpdate(UpdateView):
    model = Persona
    # fields = ['nombre_persona','apellido','edad','comunidad']
    form_class = PersonaForm
    template_name_suffix = '_crear'

    @method_decorator(permission_required('control.change_persona',reverse_lazy('control:personas')))
    def dispatch(self, *args, **kwargs):
            return super(PersonaUpdate, self).dispatch(*args, **kwargs)

class PersonaDelete(DeleteView):
    model = Persona
    success_url = reverse_lazy('control:personas')
    template_name_suffix = '_eliminar'

    @method_decorator(permission_required('control.delete_persona',reverse_lazy('control:personas')))
    def dispatch(self, *args, **kwargs):
            return super(PersonaDelete, self).dispatch(*args, **kwargs)

# ------------------------------------

class ComunidadCreate(CreateView):
    model = Comunidad
    # fields = '__all__'
    form_class = ComunidadForm
    success_url = reverse_lazy('control:comunidades')
    template_name_suffix = '_crear'

    @method_decorator(permission_required('control.add_persona',reverse_lazy('control:comunidades')))
    def dispatch(self, *args, **kwargs):
            return super(ComunidadCreate, self).dispatch(*args, **kwargs)

class ComunidadUpdate(UpdateView):
    model = Comunidad
    # fields = ['nombre_comunidad','departamento','municipio']
    form_class = ComunidadForm
    success_url = reverse_lazy('control:comunidades')
    template_name_suffix = '_crear'

    @method_decorator(permission_required('control.change_persona',reverse_lazy('control:comunidades')))
    def dispatch(self, *args, **kwargs):
            return super(ComunidadUpdate, self).dispatch(*args, **kwargs)

class ComunidadDelete(DeleteView):
    model = Comunidad
    success_url = reverse_lazy('control:comunidades')
    template_name_suffix = '_eliminar'

    @method_decorator(permission_required('control.delete_persona',reverse_lazy('control:comunidades')))
    def dispatch(self, *args, **kwargs):
            return super(ComunidadDelete, self).dispatch(*args, **kwargs)

# ------------------------------------

class ActividadCreate(CreateView):
    model = Actividad
    # fields = '__all__'
    form_class = ActividadForm
    success_url = reverse_lazy('control:actividades')
    template_name_suffix = '_crear'

    def get_context_data(self, **kwargs):
        context = super(ActividadCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['actividadespar'] = PartActFormSet(self.request.POST)
        else:
            context['actividadespar'] = PartActFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        actividadespar = context['actividadespar']
        if actividadespar.is_valid():
            response = super().form_valid(form)
            actividadespar.instance = self.object
            actividadespar.save()
            return response
        else:           
            return super(ActividadCreate, self).form_valid(form)

    @method_decorator(permission_required('control.add_persona',reverse_lazy('control:actividades')))
    def dispatch(self, *args, **kwargs):
            return super(ActividadCreate, self).dispatch(*args, **kwargs)


class ActividadUpdate(UpdateView):
    model = Actividad
    # fields = '__all__'
    form_class = ActividadForm
    success_url = reverse_lazy('control:actividades')
    template_name_suffix = '_crear'

    def get_context_data(self, **kwargs):
        context = super(ActividadUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['actividadespar'] = PartActFormSet(self.request.POST, instance=self.object)
            context['actividadespar'].full_clean()
        else:
            context['actividadespar'] = PartActFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        actividadespar = context['actividadespar']
        if actividadespar.is_valid():
            response = super().form_valid(form)
            actividadespar.instance = self.object
            actividadespar.save()
            return response
        else:
            return super(ActividadCreate, self).form_valid(form)

    @method_decorator(permission_required('control.change_persona',reverse_lazy('control:actividades')))
    def dispatch(self, *args, **kwargs):
            return super(ActividadUpdate, self).dispatch(*args, **kwargs)

class ActividadDelete(DeleteView):
    model = Actividad
    success_url = reverse_lazy('control:actividades')
    template_name_suffix = '_eliminar'

    @method_decorator(permission_required('control.delete_persona',reverse_lazy('control:actividades')))
    def dispatch(self, *args, **kwargs):
            return super(ActividadDelete, self).dispatch(*args, **kwargs)

grupo/control/templates/control/actividad_crear.html
{% extends "control/main_template.html" %}

{% load static %}

{% block title %}<title>Agregar</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

            <div class="col-md-12">
                    <h1>Agregar Actividad</h1> 
                <br>
            </div>             

        <div class="col-lg-12">
                <div class="card">
                        <div class="card-header">
                            <strong>Datos de la Persona</strong>
                        </div>

                    <div class="card-body card-block">
                        <form action="" method="post" class="">
                            <div class="form-group">
                            {% csrf_token %}
                                
                                <div class="row form-group">
                                        {% for field in form %}
                                        <div class="col col-md-12">
                                            <label for="" id="{{ field.id_for_label }}" class="form-control-label">{{ field.label_tag }}</label>
                                            {{ field }} 
                                        </div>
                                        <div class="col-12 col-md-9">
                                            
                                            <br>                                  
                                        </div>
                                        {% endfor %}
                                </div>

                            </div>
                    </div>
                         
                            <div class="card-header">
                                    <strong>Participantes de la Actividad</strong>
                                </div>
                                
                                <table class="table">
                                    {{ actividadespar.management_form }}
                    
                                    {% for form in actividadespar.forms %}
                                        {% if forloop.first %}
                                            <thead>
                                            <tr>
                                                {% for field in form.visible_fields %}
                                                    <th>{{ field.label|capfirst }}</th>
                                                {% endfor %}
                                            </tr>
                                            </thead>
                                        {% endif %}
                                            <tr class="formset_row-{{ formset.prefix }}">
                                                {% for field in form.visible_fields %}
                                                    <td>
                                                        {# Include the hidden fields in the form #}
                                                        {% if forloop.first %}
                                                            {% for hidden in form.hidden_fields %}
                                                                {{ hidden }}
                                                            {% endfor %}
                                                        {% endif %}
                                                        {{ field.errors.as_ul }}
                                                        {{ field }}
                                                    </td>
                                                {% endfor %}
                                            </tr>
                                    {% endfor %}
                                </table> 

                            <div class="card-footer">
                                <a href="{% url 'control:actividades' %}"><button type="button" class="btn btn-secondary btn-sm">Cancelar</button></a>
                                <button type="submit" class="btn btn-success btn-sm pull-right">Agregar</button>
                            </div>
                        </form>
                </div>
        </div>
        
    </div>

    <!-- Scripts necesarios para utilizar el script de la tabla -->
    <script src="{% static 'vendor/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'formset/jquery.formset.js' %}"></script>
    
    <!-- Script para agregar o quitar filas de la tabla Participantes -->
    <script type="text/javascript">
        $('.formset_row-{{ formset.prefix }}').formset({
            addText: 'Agregar otro Participante',
            deleteText: 'Quitar',
            prefix: '{{ formset.prefix }}',
        });
    </script>

    
   
{% endblock content %}

grupo/control/templates/control/actividad_detail.html
{% extends "control/main_template.html" %}

{% load static %}

{% block title %}<title>Detalles</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30"> 
    
        <div class="col-md-12">
            <h2>Detalle Actividad</h2> 
            <br>
        </div>          

        <div class="col-lg-6.offset-md-3">
                <div class="card">
                    <div class="card-header">Detalle de la Actividad</div>

                    <div class="card-body card-block">
                            <p><strong>Nombre:</strong> {{ actividad.nombre_actividad }}</p>
                            <p><strong>Descripcion:</strong> {{ actividad.descripcion }}</p>
                            <p><strong>Fecha:</strong> {{ actividad.fecha }}</p>    
                            <p><strong>Lugar:</strong> {{ actividad.lugar }}</p> 
                    </div>

                    <div style="margin-left:20px;margin-top:20px">
                        <h4>Participantes</h4>
                    
                        {% for participante in actividad.participantes_actividad_set.all %}
                        <hr>                        
                        <p><strong>Participante:</strong> {{participante.persona}}</p>
                        
                        {% endfor %}
                    </div>

                    <div class="card-footer">
                        <a href="{% url 'control:actividades' %}"><button type="button" class="btn btn-secondary btn-sm">Regresar</button></a>
                    </div>
                        
                </div>
        </div> 

        

    </div>

{% endblock content %}

grupo/control/templates/control/actividad_eliminar.html
{% extends "control/main_template.html" %}

{% load static %}

{% block title %}<title>Eliminar</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Eliminar</h1> 
                <br>

                <p>Estas seguro que deseas eliminar la Actividad: </p>
                <strong>"{{ actividad }}"</strong>
                <br><br>

                    <form action="" method="POST">
                    {% csrf_token %}          
                    <a href="{% url 'control:comunidades' %}"><button type="button" class="btn btn-secondary btn-sm">Cancelar</button></a> 
                    <button type="submit" class="btn btn-success btn-sm">Confirmar</button>
                    <br>
                    </form>
        </div>          
   
    </div>
   
{% endblock content %}

grupo/control/templates/control/actividad_list.html
{% extends "control/main_template.html" %}

{% load static %}

{% block title %}<title>Listado</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Actividades</h1> 
                {% if perms.control.add_persona %}
                <a href="{% url 'control:actividad_create' %}" class="pull-right"><button type="button" class="au-btn au-btn-icon au-btn--green au-btn--small pull-right">Agregar</button></a>
                {% endif %}
                <br><br>
        </div>          

        <div class="col-md-12">
            <div class="table-responsive table--no-card m-b-30">
                <table class="table table-borderless table-striped table-earning">

                    <thead>
                        <tr>
                            <th>Nombre Actividad</th>
                            <th>Descripcion</th>
                            <th>Fecha</th>
                            <th>Lugar</th>
                            {% if user.is_authenticated %}
                            <th style="text-align: center;">Accion</th>
                            {% endif %} 

                        </tr>
                    </thead>

                    <tbody>
                        {% if actividad_list %}

                            {% for actividad in actividad_list %}                     
                                <tr>
                                    <td>{{ actividad.nombre_actividad }}</td>
                                    <td>{{ actividad.descripcion }}</td>
                                    <td>{{ actividad.fecha }}</td>
                                    <td>{{ actividad.lugar }}</td>

                                    {% if user.is_authenticated %}
                                    <td style="text-align: center;">
                                        {% if perms.control.view_actividad %}<a href="{{ actividad.get_absolute_url }}"><img src="{% static 'images/icon/view.png' %}" width="25" height="25"/></a>{% endif %}  
                                        {% if perms.control.change_actividad %}<a href="{% url 'control:actividad_update' actividad.id %}"><img src="{% static 'images/icon/update.png' %}" width="25" height="25"/></a>{% endif %}  
                                        {% if perms.control.delete_actividad %}<a href="{% url 'control:actividad_delete' actividad.id %}"><img src="{% static 'images/icon/delete.png' %}" width="25" height="25"/></a>{% endif %}  
                                    </td> 
                                    {% endif %}                                 

                                </tr>
                            {% endfor %}                      
                            
                            {% endif %}   
                    </tbody>
                </table>     
                        
            </div>
        </div>

    </div>
   
{% endblock content %}

grupo/control/templates/control/comunidad_detail.html
{% extends "control/main_template.html" %}

{% load static %}

{% block title %}<title>Detalles</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30"> 
    
        <div class="col-md-12">
            <h2>Detalle Comunidad</h2> 
            <br>
        </div>          

        <div class="col-lg-6.offset-md-3">
                <div class="card">
                    <div class="card-header">Detalle de la Comunidad</div>

                    <div class="card-body card-block">
                            <p><strong>Nombre:</strong> {{ comunidad.nombre_comunidad }}</p>
                            <p><strong>Departamento:</strong> {{ comunidad.departamento }}</p>
                            <p><strong>Municipio:</strong> {{ comunidad.municipio }}</p>    
                    </div>

                    <div style="margin-left:20px;margin-top:20px">
                            <h4>Miembros</h4>
                        
                            {% for miembro in comunidad.persona_set.all %}
                            <hr>                        
                            <p><strong>Miembro:</strong> {{miembro.nombre_persona}}</p>
                            
                            {% endfor %}
                        </div>

                    <div class="card-footer">
                        <a href="{% url 'control:comunidades' %}"><button type="button" class="btn btn-secondary btn-sm">Regresar</button></a>
                    </div>
                        
                </div>
        </div> 
    </div>

{% endblock content %}

grupo/control/templates/control/comunidad_list.html
{% extends "control/main_template.html" %}

{% load static %}

{% block title %}<title>Listado</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Comunidad</h1> 
                {% if perms.control.add_persona %}
                <a href="{% url 'control:comunidad_create' %}" class="pull-right"><button type="button" class="au-btn au-btn-icon au-btn--green au-btn--small pull-right">Agregar</button></a>
                {% endif %}
                <br><br>
        </div>          

        <div class="col-md-12">
            <div class="table-responsive table--no-card m-b-30">
                <table class="table table-borderless table-striped table-earning">

                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Departamento</th>
                            <th>Municipio</th>
                            {% if user.is_authenticated %}
                            <th style="text-align: center;">Accion</th>
                            {% endif %} 

                        </tr>
                    </thead>

                    <tbody>
                        {% if comunidad_list %}

                            {% for comunidad in comunidad_list %}                     
                                <tr>
                                    <td>{{ comunidad.nombre_comunidad }}</td>
                                    <td>{{ comunidad.departamento }}</td>
                                    <td>{{ comunidad.municipio }}</td>

                                    {% if user.is_authenticated %}
                                    <td style="text-align: center;">
                                        {% if perms.control.view_comunidad %}<a href="{{ comunidad.get_absolute_url }}"><img src="{% static 'images/icon/view.png' %}" width="25" height="25"/></a>{% endif %}  
                                        {% if perms.control.change_comunidad %}<a href="{% url 'control:comunidad_update' comunidad.id %}"><img src="{% static 'images/icon/update.png' %}" width="25" height="25"/></a>{% endif %}  
                                        {% if perms.control.delete_comunidad %}<a href="{% url 'control:comunidad_delete' comunidad.id %}"><img src="{% static 'images/icon/delete.png' %}" width="25" height="25"/></a>{% endif %}  
                                    </td>  
                                    {% endif %}                                

                                </tr>
                            {% endfor %}                      
                            
                            {% endif %}   
                    </tbody>
                </table>     
                        
            </div>
        </div>

    </div>
   
{% endblock content %}

grupo/control/templates/control/persona_list.html
{% extends "control/main_template.html" %}

{% load static %}

{% block title %}<title>Listado</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Personas</h1> 
                {% if perms.control.add_persona %}
                <a href="{% url 'control:persona_create' %}" class="pull-right"><button type="button" class="au-btn au-btn-icon au-btn--green au-btn--small pull-right">Agregar</button></a>
                {% endif %}
                <br><br>
        </div>          

        <div class="col-md-12">
            <div class="table-responsive table--no-card m-b-30">
                <table class="table table-borderless table-striped table-earning">

                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Edad</th>
                            <th>Comunidad</th>
                            {% if user.is_authenticated %}
                            <th style="text-align: center;">Accion</th>
                            {% endif %} 

                        </tr>
                    </thead>

                    <tbody>
                        {% if persona_list %}

                            {% for persona in persona_list %}                     
                                <tr>
                                    <td>{{ persona.nombre_persona }}</td>
                                    <td>{{ persona.apellido }}</td>
                                    <td>{{ persona.edad }}</td>
                                    <td>{{ persona.comunidad }}</td>
                                    
                                    {% if user.is_authenticated %}
                                    <td style="text-align: center;">
                                        {% if perms.control.view_persona %}<a href="{{ persona.get_absolute_url }}"><img src="{% static 'images/icon/view.png' %}" width="25" height="25"/></a>  {% endif %}
                                        {% if perms.control.change_persona %}<a href="{% url 'control:persona_update' persona.id %}"><img src="{% static 'images/icon/update.png' %}" width="25" height="25"/></a>{% endif %}  
                                        {% if perms.control.delete_persona %}<a href="{% url 'control:persona_delete' persona.id %}"><img src="{% static 'images/icon/delete.png' %}" width="25" height="25"/></a>{% endif %} 
                                    </td> 
                                    {% endif %}                                

                                </tr>
                            {% endfor %}                      
                            
                            {% endif %}   
                    </tbody>
                </table>     
                        
            </div>
        </div>
    </div>
   
{% endblock content %}